name: Test

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  Test:
    name: Go1.19
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.19
        uses: actions/setup-go@v2
        with:
          go-version: "1.19"
      - name: Check out code
        uses: actions/checkout@v2
      - name: Test
        run: go test -v -coverprofile="coverage.txt" ./...
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
