name: Test

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  Lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.19
        uses: actions/setup-go@v3
        with:
          go-version: "1.19"
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
  UnitTest:
    name: UnitTest
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.19
        uses: actions/setup-go@v3
        with:
          go-version: "1.19"

      - name: Check out code
        uses: actions/checkout@v3
      - name: Test
        run: go test -v -coverprofile="coverage.txt" ./...
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
